### PR TITLE
Send sns notifications from ERT on select errors

### LINKED ISSUE #156: Include ERT log in the CloudWatch Notification.
**Summary**
Currently None of the ERT CloudWatch alerts give us specific details on the the exchange rate the was pushed on the failure. 

**Possible resolution**
We should change the text in the alert. If the ERT does smoothing because the median exchange rate changed too much since midnight, then the alert should include:

- the exchange rate at midnight (in cents per hbar)

- The exchange rate it would have changed to without the clipping

- The exchange rate it did change to, because of the clipping.

Those numbers will help in diagnosing whether there is something actually wrong, or the true exchange rate is simply changing very fast.

### PR DESCRIPTION
**Pull request by anighanta**
**Related issue(s)**:
Closes #156 #178 

**Summary of the change**:
Enhanced ERT to send SNS notifications with appropriate details about the error directly to a configured slack channel rather then relying on AWS CloudWatch which doesn't allow us much flexibility.

**Applicable documentation**
- [ ] Javadoc
- [ ] tests
- [ ] README

### CODE REVIEW

File: src/main/java/com/hedera/exchange/ExchangeRateTool.java [hunk 1]
```diff
@@ -212,7 +225,15 @@ protected void fileUpdateTransactionForNetwork(
...
                     }
                     return;
-                } catch (Exception ex) {
+                }
+                catch (ReceiptStatusException rex) {
+                    // Only retry if its not ReceiptStatusException as it is already handled in
+                    // HederaNetworkCommunicator.updateExchangeRateFileTxn
+                    LOGGER.error(Exchange.EXCHANGE_FILTER,
+                            "Failed to update the network withe calculated rates with 4 retries.");
+                    return;
```
Comment (Neeharika-Sompalli) [inline src/main/java/com/hedera/exchange/ExchangeRateTool.java:234]: nit : no need return here

**Review by Neeharika-Sompalli — APPROVED** [review]

**Review by tinker-michaelj — APPROVED** [review]
Everything makes sense to me!
